#!/usr/bin/env bash

usage="Gets tShock running server status. Output 0 if running, 1 other way.

Usage: $(basename "$0")"

function healthCheck(){
    PID=$(cat ${TSHOCK_HOME}/tshock/tshock.pid 2> /dev/null)
    if [ -n "$PID" -a -e /proc/$PID ]; then
        echo "TShock running pid ${PID}."
        exit
    else
        echo "TShock is not running."
        exit 1
    fi
}

if [ $# -gt 0 ]; then
    case $1 in
        "-h"|"--help" ) shift
              echo "$usage"
              ;;
    esac
fi

healthCheck